name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Image (Broker)
      working-directory: ./broker
      run: docker build . --file Dockerfile --tag broker:$(date +%s)
    - name: Build Image (Service)
      working-directory: ./service
      run: docker build . --file Dockerfile --tag service:$(date +%s)
    - name: Build Image (Web)
      working-directory: ./web
      run: docker build . --file Dockerfile --tag web:$(date +%s)
